### ISSUE TITLE
How to access current branch / sha in gatsby-browser.js

### ISSUE THREAD

**Issue by johnnybenson** [PMudra/gatsby-source-local-git#191]
Struggling a bit to implement this info into the page tracking. 

```js
// gatsby-browser.js
exports.onRouteUpdate = ({ location, prevLocation }) => {
  window.analytics &&
    window.analytics.page({
      dimension1: CURRENT_BRANCH,
      dimension2: CURRENT_SHA,
    });
};
```
Using [`gatsby-plugin-segment-js`](https://www.gatsbyjs.org/packages/gatsby-plugin-segment-js/#track-pageviews), page tracking is configured in `gatsby-browser.js`.

Wondering if there is a way to use `gatsby-source-local-git` to read the branch in this location?

Thanks for your insight!

**Comment by johnnybenson** [comment]
I think I have a workaround. It feels like a lot of code to do something basic.

#### Higher order component for fetching Git info and page analytics
```js
// withPageTracking.js
import React from 'react';
import { StaticQuery, graphql } from 'gatsby';
import { trackPageView } from './analytics';

export default function withPageTracking(Component) {
  function PageTrackingHOC(props) {
    return (
      <StaticQuery
        query={graphql`
          query {
            gitBranch(current: { eq: true }) {
              name
              commit
            }
          }
        `}
        render={(data) =>
          trackPageView({
            dimension1: data.gitBranch.name,
            dimension2: data.gitBranch.commit,
          }) && <Component data={data} {...props} />
        }
      />
    );
  }

  return PageTrackingHOC;
}
```

#### Apply HOC to Layout
```js
// Layout.js
import React from 'react';
import cx from 'classnames';

import withPageTracking from 'components/lib/withPageTracking';
import styles from './styles.module.scss';

const Layout = ({ children }) => (
  <div className={cx('layout', styles.Layout)}>
    {children}
  </div>
);

export default withPageTracking(Layout);
```

#### Option 1: wrapPageElement
```js
// gatsby-browser.js
const React = require('react');
const Layout = require('./src/components/layout').default;

exports.wrapPageElement = ({ element, props }) => {
  // props provide same data to Layout as Page element will get
  // including location, data, etc - you don't need to pass it
  return <Layout {...props}>{element}</Layout>;
};
```

#### Option 2: MDX defaultLayouts
```js
// gatsby-config.js
module.exports = {
  plugins: [
    `gatsby-source-local-git`,
    {
      resolve: `gatsby-plugin-mdx`,
      options: {
        defaultLayouts: {
          default: require.resolve('./src/components/Layout/index.js'),
        },
      },
    },
  }
}
```

I'm kinda new, it seems like _when data is available_ and _where data is available_ between build and run time is a just a smell thing with Gatsby! 

Somewhat related: https://github.com/benjaminhoffman/gatsby-plugin-segment-js/issues/13#issuecomment-473574271

**Comment by PMudra** [comment]
That is an interesting use case of this plugin I haven't thought of until now.

Just some thoughts / ideas:

1. Check if there is any way to access query data in `onRouteUpdate`. That would be the best way to go.
2. Is `wrapPageElement` called as regularly as `onRouteUpdate` on every page load?
3. If 2 is true, can you use `StaticQuery` in `wrapPageElement`? Maybe you can remove some boilerplate.
4. For sure you can use the `useStaticQuery` hook as an improvement. It basically let's you query data without that HOC. You might use that hook directly in `wrapPageElement` if possible.

It is true that the whole handling of data is not always straightforward. Let me now if you figure it out.

**Comment by johnnybenson** [comment]
Thanks for your thoughts.

# 1 is also my preferred path forward, I couldn't finding any clues for accessing query data there.

# 2, 4 `wrapPageElement` does seem to be called once when moving between pages when they're rendered so it's working well enough.  

FWIW, the above is working. The hook could remove some boilerplate, would be nicer, I'll give it a try. Cheers!
