### ISSUE TITLE
Add the raw diff to each commit

### ISSUE THREAD

**Issue by ncuillery** [PMudra/gatsby-source-local-git#228]
Hey, would you accept a PR that adds the diff to each commit? 

Something that could be parsed by users with [diff2html](https://www.npmjs.com/package/diff2html) or highlighted with [prismjs](https://prismjs.com/).

I'm currently using my own plugin because of this feature, I would love using this one.

**Comment by PMudra** [comment]
Hi @ncuillery! That sounds like a useful feature. Please go ahead and let me know if you need any help.

**Comment by ncuillery** [comment]
Oh I'm sorry, forgot to put an update here.

I realized that this plugin only exposes the current repo in the current folder. I need to get the history of a external repo.

I kept my home-made plugin for now. If you or someone else want to implement this, here is my code for getting the diff:

```typescript
const readDiff = async (commits: SimpleGitCommit, show: SimpleGitShow, folder: string) => {
  console.log(commits.length + " commits found");
  const diffs: DiffDictionary = {};
  for (let i = 0; i < commits.length; i++) {
    const diff = await show([commits[i].hash, "--patch", '--format=format:""', '--', folder]);
    diffs[commits[i].hash] = diff;
  }
  return diffs;
};
```

The last parameter `folder` had the ability to extract the diff from a particular folder inside the repo. I needed it, but it may have its place in a general-purpose plugin like this one

**Comment by PMudra** [comment]
Thanks for the update. I will close this issue for now.
