### ISSUE TITLE
Would it be possible to include the files modified in a commit?

### ISSUE THREAD

**Issue by tupini07** [PMudra/gatsby-source-local-git#285]
It would be very useful if we could access the list of files that were edited in a given commit (or _allCommit_). A use case would be to know which commits modified a given file.

For example, the following query:

```
{
  allGitCommit {
    nodes {
      author {
        email
        name
      }
      date(locale: "UTC")
      files
    }
  }
}
```

Could generate the following output

```
{
  "data": {
    "allGitCommit": {
      "nodes": [
        {
          "author": {
            "email": "example@gmail.com",
            "name": "Ex Ample"
          },
          "date": "2020-07-16T18:40:27.000Z"
          "files": [
            "/path/to/some/file1",
            "/path/to/some/file2",
          ]
        },
.......
```

Maybe in the future also include more options on the file like selecting the _name_, _path_, etc.

**Comment by PMudra** [comment]
Thanks for the request. Nice idea. I am sure this can be done quiet easily and I will have a look in the next days.
For sure we have to check if this feature will perform badly on large repositories with many commits. Maybe the plugin has to support some option to limit the amount of commits.

**Comment by PMudra** [comment]
Please feel free to try out the new version v1.1.0. Any feedback is welcome!
