### ISSUE TITLE
Gatsby v4 support?

### ISSUE THREAD

**Issue by CSharperMantle** [PMudra/gatsby-source-local-git#559]
Currently the plugin only supports Gatsby v2-3. Upgrading the plugin to support Gatsby v4 may allow this plugin to be used by more people.

I have done some experimental migration steps in [my own fork](https://github.com/CSharperMantle/gatsby-source-local-git-modern) of the project. It would be better if these changes can be officially done by @PMudra, the original author.

**Comment by PMudra** [comment]
Hi @CSharperMantle, thanks for reaching out. I haven't looked into Gatsby v4 and the migration steps for plugins like this one. I would be happy to support Gatsby v4. Please feel free to create a pull requests with your current work.

**Comment by CSharperMantle** [comment]
Hi @PMudra ,

Thanks for your response! :wink:

Changes required to make the package compat with Gatsby v4 are breaking (to extract `createTypes` calls into an extra exported method `createSchemaCustomization`, which do not get recognized in Gatsby@^3.0.0 and below, specifically) so I think I'd better fork the project and release a new package to maintain compatibility.

Many thanks again for this amazing Gatsby plugin!

**Comment by PMudra** [comment]
Hi @CSharperMantle, I have released a new version of this plugin v1.3.0 that supports Gatsby v4! Please feel free to try that out and report any problems if there are any.
